/**
 * CSRD-Lake dashboard data accessors.
 *
 * Reads from `data/disclosures.json`, which is generated by
 * `scripts/export_dashboard_data.py` querying the local DuckDB warehouse
 * after `dbt run`. The JSON is committed so Vercel builds work without
 * needing access to the warehouse file.
 *
 * Re-export the snapshot:
 *   uv run python scripts/export_dashboard_data.py
 */

import disclosuresSnapshot from "./data/disclosures.json";

export type Company = {
  ticker: string;
  name: string;
  sector: string;
  country: string;
  language: "fr" | "en";
};

export type ExtractionModel = "claude-sonnet-4-6" | "mistral-large-latest";
export type EsrsTopic = "E1" | "E2" | "E3" | "S1" | "G1";

export type DisclosureMetric = {
  id: string;
  esrsTopic: EsrsTopic;
  esrsDisclosure: string;
  metricName: string;
  valueNumeric: number | null;
  valueText: string | null;
  unit: string | null;
  confidenceScore: number; // [0, 1]
  sourcePage: number;
  sourceSnippet: string;
  language: "fr" | "en";
  extractionModel: ExtractionModel;
};

export type CompanyDisclosures = {
  company: Company;
  fiscalYear: number;
  metrics: DisclosureMetric[];
};

// ── Snapshot wiring ───────────────────────────────────────────────────

type Snapshot = {
  fiscalYear: number;
  extractedAt: string;
  companies: Company[];
  disclosuresByTicker: Record<string, DisclosureMetric[]>;
};

const SNAPSHOT = disclosuresSnapshot as Snapshot;

export const COMPANIES: readonly Company[] = SNAPSHOT.companies;

export const SNAPSHOT_EXTRACTED_AT: string = SNAPSHOT.extractedAt;

// ── Public accessors ──────────────────────────────────────────────────

export function getAllCompanies(): readonly Company[] {
  return COMPANIES;
}

export function getCompanyByTicker(ticker: string): Company | undefined {
  return COMPANIES.find((c) => c.ticker === ticker);
}

export function getDisclosuresByTicker(
  ticker: string,
): CompanyDisclosures | undefined {
  const company = getCompanyByTicker(ticker);
  if (!company) return undefined;
  const metrics = SNAPSHOT.disclosuresByTicker[ticker] ?? [];
  return { company, fiscalYear: SNAPSHOT.fiscalYear, metrics };
}

// ── Portfolio rollup (synthetic exposure map over real Scope 1 data) ──
//
// The exposureEurMillions values are a CLEARLY-LABELED synthetic loan book
// used to demonstrate what the warehouse data could power for a corporate
// banking team. The Scope 1 emissions are real — pulled from extracted
// disclosures when available, null otherwise.

export type PortfolioExposure = {
  company: Company;
  exposureEurMillions: number;
  scope1Emissions: number | null; // tCO2e
  emissionsPerEurMillion: number | null;
};

const SYNTHETIC_EXPOSURE_EUR_M: Record<string, number> = {
  "MC.PA": 320,
  "TTE.PA": 850,
  "BNP.PA": 120,
  "SAN.PA": 540,
  "CS.PA": 410,
  "ORA.PA": 280,
  "OR.PA": 360,
  "SU.PA": 220,
  "AI.PA": 480,
  "SGO.PA": 290,
};

function findScope1ForTicker(ticker: string): number | null {
  const metrics = SNAPSHOT.disclosuresByTicker[ticker] ?? [];
  // Prefer published-mart-eligible (confidence >= 0.80) Scope 1 row if present.
  const scope1Rows = metrics.filter(
    (m) =>
      m.esrsDisclosure === "E1-6" &&
      m.metricName.toLowerCase().includes("scope 1") &&
      m.valueNumeric !== null,
  );
  const chosen =
    scope1Rows.find((m) => m.confidenceScore >= 0.8) ?? scope1Rows[0];
  return chosen?.valueNumeric ?? null;
}

export function getPortfolioExposures(): PortfolioExposure[] {
  return COMPANIES.map((company) => {
    const scope1 = findScope1ForTicker(company.ticker);
    const exposureEurMillions = SYNTHETIC_EXPOSURE_EUR_M[company.ticker] ?? 0;
    const emissionsPerEurMillion =
      scope1 !== null && exposureEurMillions > 0
        ? Math.round(scope1 / exposureEurMillions)
        : null;
    return {
      company,
      exposureEurMillions,
      scope1Emissions: scope1,
      emissionsPerEurMillion,
    };
  });
}

export function getPortfolioTotals(): {
  totalExposureEurMillions: number;
  totalScope1Emissions: number;
  weightedEmissionsIntensity: number;
  companyCount: number;
} {
  const exposures = getPortfolioExposures();
  const totalExposureEurMillions = exposures.reduce(
    (acc, e) => acc + e.exposureEurMillions,
    0,
  );
  const totalScope1Emissions = exposures.reduce(
    (acc, e) => acc + (e.scope1Emissions ?? 0),
    0,
  );
  const weightedEmissionsIntensity =
    totalExposureEurMillions > 0
      ? Math.round(totalScope1Emissions / totalExposureEurMillions)
      : 0;
  return {
    totalExposureEurMillions,
    totalScope1Emissions,
    weightedEmissionsIntensity,
    companyCount: exposures.filter((e) => e.scope1Emissions !== null).length,
  };
}
